# Base docker-compose file with infrastructure settings

## Services are injected from docker-compose file of started components (proxy, agents, ...).

## Networks available for all services
networks:
  # network for agents to not be able to access internet directly, but to force them to proxy all requests
  sandbox:
    internal: true
  # network for proxy container with access to internet
  internet:
    driver: bridge
